### PR TITLE
Api token

### PR DESCRIPTION
**Pull request by alice-carr**
#### What problem does the pull request solve?
We will be adding an API to api - see this pr: https://github.com/alphagov/forms-api/pull/38
This pr passes in the token via the header

todo:
- [x] add api token as secret to this repo

#### Checklist

- [x] I've used the pull request template
- [x] I've written unit tests for these changes (if code change)
- [x] I've updated the documentation in (If any documentation requires updating)
    - [x] README.md

### CODE REVIEW

**Review by DavidBiddle — APPROVED** [review]
looks good to me 🎉

**Review by aliuk2012 — COMMENTED** [review]
Looks good to me, any chance we could tidy up the commit history and drop some of the merge commits?

**Comment by alice-carr** [comment]
> Looks good to me, any chance we could tidy up the commit history and drop some of the merge commits?

yeah no problem, I'll do that now

**Comment by alice-carr** [comment]
well, completely failed squashing those commits. Instead of messing around with git further I'm going to go the old fashioned route and just close this and make a new pr. lesson learned!

**Comment by alice-carr** [comment]
New PR here: https://github.com/alphagov/forms-runner/pull/83
closing this one

**Pull request closed without merging**
